---
- name: Gather and store facts
  hosts: windows
  gather_facts: yes
  become: yes
  become_method: runas
  tasks:
    - name: Copy facts to file
      ansible.windows.win_copy:
        content: |
          OS: "{{ ansible_facts['os_name'] }}"
          FQDN: "{{ ansible_facts['fqdn'] }}"
          Domain: "{{ ansible_facts['windows_domain'] }}"
          Machine ID: "{{ ansible_facts['machine_id'] }}"
          Last Boot: "{{ ansible_facts['lastboot'] }}"
          IP Addresses: "{{ ansible_facts['ip_addresses'] }}"
        dest: "{{ ansible_facts['user_dir'] }}\\Desktop\\summary-{{ ansible_facts['hostname'] }}.txt"
